### ISSUE TITLE
Changing Icons through the client resets level

### ISSUE THREAD

**Issue by Cedsi56** [4dams/LeagueToolkit#1]
When you change your icon through the change icon menu on the client (which appears when you click on your icon), your level, rank, custom availability, basically everything will go back to normal.

How to reproduce :
1) Change your settings (put yourself at challenger and lvl 1337 and with the name "Big boi" for example)
2) Click on your icon
3) Choose another icon and press "SAVE"
4) Your settings are now back to normal!

**Comment by Xh4H** [comment]
Fixed as well as a result of fixing #4
