### ISSUE TITLE
Summoner Backdrops

### ISSUE THREAD

**Issue by ghost** [4dams/LeagueToolkit#15]
can we add summoner backdrops?
https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/summoner-backdrops/1425.webm

**Comment by juriadams** [comment]
Hey there! Thanks for the idea!

We've already looked into this, but unfortunately, it's not working for backrounds/skins you don't own...

However, it should be working for owned backgrounds/skins, which would be a great implementation for the upcoming "profiles" tab.

The toolkit will be completely rebuilt in the future to run better, smoother and faster, we'll then also implement this!

Thank you very much for your feedback!
