### ISSUE TITLE
Css Background Image 404 Error

### ISSUE THREAD

**Issue by ghost** [4dams/LeagueToolkit#16]
https://i.4da.ms/Gch1r6.png not working to me. (maybe)

I added this image to the background.(https://image.ibb.co/nuqyYo/lcu_alpha_backdrop.jpg)

**Comment by juriadams** [comment]
Fixed!

Recently updated my cdn and moved some files.
In the dev version it's already a local file, that's why I didn't notice. 

Thanks for your help! ;)
