### ISSUE TITLE
I got a question. (Irrelevant)

### ISSUE THREAD

**Issue by ghost** [4dams/LeagueToolkit#17]
What do I have to do to change the writing in it? 

Ex: "Play" => "Lose LP"
![screenshot_1](https://user-images.githubusercontent.com/41707210/43491575-bf81c754-952d-11e8-8ce2-1a8709114954.png)

**Comment by lakema17** [comment]
Pretty sure you have to edit the actual client itself for that, something this tool doesn't do.

**Comment by Xh4H** [comment]
> Pretty sure you have to edit the actual client itself for that, something this tool doesn't do.

Correct, this tool only edits what people see about your profile, such as wins, rank, etc.
