### ISSUE TITLE
Custom status message don't work!

### ISSUE THREAD

**Issue by Cedsi56** [4dams/LeagueToolkit#2]
When trying to use the custom status message feature, you might realize that it doesn't work.
You should be able to change the "Online" under your level when your mouse is hovering your icon, but it seems to be broken.

How to reproduce :

1) Change your status message using the app
2) Hover your icon: it didnt work :'(

**Comment by juriadams** [comment]
[Fixed](https://github.com/4dams/LeagueToolkit/commit/80a7326a40b08bfc9d60637adcae58505b6b5b74)
