### ISSUE TITLE
Gaining exp puts your level back to normal

### ISSUE THREAD

**Issue by Cedsi56** [4dams/LeagueToolkit#4]
With the tool, you can change your level to whatever you want, and it's very nice 👍 
However, after an harsh game (or a 5min open because your mid's mom is calling him), you get exp; the problem being that it sets your level back to normal, which means you have to set it back to whatever value you wanted. 

How to reproduce :

1) Change your level using the app
2) Play a game in which you'll gain exp (must be over 7 min long)
3) When the game ends, honor your support (because he is a god) and check your level. It has been changed back to normal!

Note :
If the game is a practise tool game, you won't get exp, and your custom level will be kept
ONLY the level will be affected by the bug; not the custom ranks, names ...
If you don't honor your support, I'll find you, and I'll report you.

**Comment by juriadams** [comment]
Funny description! +1

**Comment by Xh4H** [comment]
Fixed. Sorry for the delay.
