### ISSUE TITLE
I'm interested, though, what does it do? Can I be banished?

### ISSUE THREAD

**Issue by Suburbanno** [4dams/LeagueToolkit#7]

**Comment by juriadams** [comment]
Hello!

Thank you for the interest in my project!
At the current state of time, the project is still not finished and under development, as you may have already seen on the README-file. 

What I'm building here, is a small application called "LeagueToolkit" which allows you to "modify" some information/stats/data in the updated League of Legends client. 

For example, it let's you display a custom rank (from unranked up to challenger), a custom level and a few more things, just to sum some of the features up.

I'm also planning on automating the process of the champ select, allowing the tool to automatically accept the ready check, choose a role and champion, select runes and summoner spells. Maybe even define those things according to enemy matchups and common counterplays, who knows?

More about the specific features and why I'm doing all this will follow soon on the main page of this repository!

And to answer your question about getting banned: There have been some tools like this before working with the old client, even some chat apps which are still working today letting you customize some stuff. 
There are no known incidents of people who got banned for using these kind of apps. :)
Plus, my application does nowhere near affect gameplay or even touches the main game.

So I'd say that the tool is pretty much safe to use, in aspect of getting banned.
I just want to note: This tool is not confirmed by Riot Games or officially allowed. This is just my experience so far.

**Comment by Suburbanno** [comment]
i really want to test the LeagueToolkit @4dams

**Comment by juriadams** [comment]
As you can see on the [previews page](https://github.com/4dams/LeagueToolkit/blob/master/PREVIEWS.md), I'm currently really close on publishing a first build!

I'm planning on doing so tomorrow!

**Comment by Suburbanno** [comment]
I'm excited  D:

**Comment by Suburbanno** [comment]
@4dams

**Comment by juriadams** [comment]
First **unstable** testing version of the app has been released! :)

https://github.com/4dams/LeagueToolkit/releases
