### ISSUE TITLE
JavaScript ERROR

### ISSUE THREAD

**Issue by Suburbanno** [4dams/LeagueToolkit#8]
I can not use LeagueToolkit, I receive this error without stopping, making the program unusable.
![error1](https://user-images.githubusercontent.com/13632826/36673616-10aec8dc-1ae2-11e8-8bc6-4a485e69a3eb.PNG)

**Comment by juriadams** [comment]
Hmm, I see...

- Are currently logged in in the League Client?
- Have you tried restarting both the client and the app?
- Did you correctly unzip the file and placed **all** of its contents into a new folder?

Please make sure you have done all these things, app is working fine for other testers, even on my clean Windows 10 box.

**Comment by Suburbanno** [comment]
I did all the processes, executed as administrator, and the error remains

**Comment by Suburbanno** [comment]
The account I'm testing is unrranked, would that be the problem?

**Comment by juriadams** [comment]
I'm taking a look into this right now. Give me a bit.

**Comment by juriadams** [comment]
[Fixed](https://github.com/4dams/LeagueToolkit/commit/39ddfc426a358b69a7d3e36220bbf06d212ae107)

Release will be updated within the next few minutes.

**Comment by juriadams** [comment]
New release including hotfix uploaded!
