### ISSUE TITLE
modifications saved for only seconds.

### ISSUE THREAD

**Issue by Suburbanno** [4dams/LeagueToolkit#9]
Well, the settings are saved for just a few seconds, using the app "League of Friends" (chat official app) the modifications appear and then disappear, do not know if it is exactly a bug, at least "Custom availability" is saved.

**Comment by juriadams** [comment]
This is probably an issue I'm not able to fix since the Chat app itself overwrites this information. There may be a fix for this in the future.

**Comment by Suburbanno** [comment]
And another thing, shouldn't the modification appear here as well?

![error3](https://user-images.githubusercontent.com/13632826/36676069-746f3cba-1ae9-11e8-9e92-c05fd005b7d5.PNG)

**Comment by juriadams** [comment]
Unfortunately, this will not be possible to change. =/

On profiles, the client pulls the information from the main Riot API itself (I believe).
Same as in champion select, when other people will see your real name.

**Comment by Suburbanno** [comment]
I understand, sorry to take up your time!

**Comment by juriadams** [comment]
Don't worry! I'm really thankful for your help and contribution to this project! Working on this app is more than fun for me and I appreciate every help I can get!
